### ISSUE TITLE
ModuleNotFoundError: No module named 'dpl'

### ISSUE THREAD

**Issue by denizkavi** [HySonLab/Protein_Redesign#1]
```
~/Protein_Redesign$ python generate.py     --ckpt_path "checkpoints/ProteinReDiff_v1.ckpt"     --output_dir "workdir/generate/example_ProteinReDiff"     --protein "LSEQLKHCNGILKELLSKKHAAYAWPFYKPVDASALGLHDYHDIIKHPMDLSTVKRKMENRDYRDAQEFAADVRLMFSNCYKYNPPDHDVVAMARKLQDVFEFRYAKMPD"     --ligand "Cc1ccc2c(c1c3cc(cc4c3nc([nH]4)C5CC5)c6c(noc6C)C)cccn2"     --num_samples 8
Traceback (most recent call last):
  File "/home/ubuntu/Protein_Redesign/generate.py", line 16, in <module>
    from dpl.data import RepeatDataset, collate_fn, ligand_to_data, protein_to_data
ModuleNotFoundError: No module named 'dpl'
```

It looks like the the conda environment setup doesn't include dpl. I've tried to clone the DPL repo directly and use the directory inside there, but that doesn't seem to be the same one as expected in this repo. Would be great if there's a way to fix this installation.

**Comment by ndnng** [comment]
We just fixed the module import. Some of the module borrowed from DPL but we have modified a lot of functions there. Thanks for being the first tester and pointing it out!
